name: ISO

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: '0 1 1 3,6,9,12 *'
    
jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Prepare
        run: mkdir output
      - name: Build 9
        run: |
          sudo podman build -t localhost/9 iso/9
          sudo podman run --privileged -v "$(pwd)/output":/output localhost/9
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: continuous
          name: Continuous
          files: |
            output/*.iso
